### ISSUE TITLE
Youtube player size on chapter 1 page is not responsive 

### ISSUE THREAD

**Issue by davinwid** [SolarChapter/old-solarchapter-website#31]
The attribute is constant, so cannot be viewed properly on smaller, handheld devices. Change to a dynamic class so can be viewed properly across all devices.

<img width="591" alt="screen shot 2018-10-28 at 9 37 02 pm" src="https://user-images.githubusercontent.com/31192484/47626539-a5501180-daf9-11e8-9df5-29ecf71bd35c.png">

**Comment by linahsie** [comment]
Fixed in PR #35
